apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "Quality Gate (Custom)"
description: "Evaluate multi-criteria quality gates per environment"
author: "Shozab Naqvi"

inputs:
  rules:
    description: "YAML rules for quality gate evaluation"
    required: true
  environment:
    description: "Target environment (qa, staging, production, etc.)"
    required: true
  critical_test_failures:
    description: "Number of critical test failures"
    required: true
  major_test_failures:
    description: "Number of major test failures"
    required: true
  minor_test_failures:
    description: "Number of minor test failures"
    required: true
  code_coverage:
    description: "Code coverage percentage"
    required: true

runs:
  using: composite
  steps:
    - id: quality-gate-check
      name: Quality Gate Check
      uses: docker://cloudbeesdemo/jira-actions:v2
      shell: sh
      run: |
        echo "=== Custom Quality Gate ==="
        echo "Environment:              ${{ inputs.environment }}"
        echo "Critical test failures:   ${{ inputs.critical_test_failures }}"
        echo "Major test failures:      ${{ inputs.major_test_failures }}"
        echo "Minor test failures:      ${{ inputs.minor_test_failures }}"
        echo "Code coverage:            ${{ inputs.code_coverage }}"
        echo
        echo "Rules:"
        echo "---------------------------"
        echo " ${{ inputs.rules }}"
        echo "---------------------------"
        echo
        echo "Not enforcing rules yet; always passing."

