apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: advanced-quality-gates
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment
        options:
          - qa
          - staging
          - production
jobs:
  quality-assessment:
    steps:
      - name: Multi-Criteria Quality Gate (custom)
        uses: ./actions/quality-gate
        with:
          environment: ${{ inputs.environment }}
          critical_test_failures: 0
          major_test_failures: 1
          minor_test_failures: 3
          code_coverage: 85
          rules: |
            # Production Rules (Strictest)
            - environment: production
              conditions:
                - metric: critical_test_failures
                  operator: equals
                  threshold: 0
                - metric: major_test_failures
                  operator: equals
                  threshold: 0
                - metric: minor_test_failures
                  operator: less_than_or_equal
                  threshold: 2
                - metric: code_coverage
                  operator: greater_than_or_equal
                  threshold: 90

            # Staging Rules (Moderate)
            - environment: staging
              conditions:
                - metric: critical_test_failures
                  operator: equals
                  threshold: 0
                - metric: major_test_failures
                  operator: less_than_or_equal
                  threshold: 1
                - metric: minor_test_failures
                  operator: less_than_or_equal
                  threshold: 5
                - metric: code_coverage
                  operator: greater_than_or_equal
                  threshold: 80

            # QA Rules (Lenient)
            - environment: qa
              conditions:
                - metric: critical_test_failures
                  operator: less_than_or_equal
                  threshold: 1
                - metric: major_test_failures
                  operator: less_than_or_equal
                  threshold: 3
                - metric: minor_test_failures
                  operator: less_than_or_equal
                  threshold: 10
                - metric: code_coverage
                  operator: greater_than_or_equal
                  threshold: 70
    needs:
      - run-test
  deploy-to-QA:
    steps:
      - name: Deploy
        uses: cloudbees-io/publish-evidence-item@v1
        run: ""
        kind: deploy
        env: {}
        with:
          content: Deployed to QA
        shell: ""
  run-test:
    steps:
      - name: Selenium
        uses: cloudbees-io/publish-evidence-item@v1
        run: ""
        kind: test
        env: {}
        with:
          content: Running Tests
        shell: ""
    needs: deploy-to-QA
  deploy-to-Staging:
    steps:
      - name: Deploy to Staging
        with:
          content: Deploy to Staging
        uses: cloudbees-io/publish-evidence-item@v1
    needs: quality-assessment
